### ISSUE TITLE
Timers - block of time

### ISSUE THREAD

**Issue by markgdev** [markgdev/home-assistant_OctopusAgile#1]
Add the option to ensure all timers are in one block for use with appliances such as washing machine.

**Comment by markgdev** [comment]
See #18 for a good usecase

**Comment by slug56** [comment]
Great job with the project! Really enjoying it in combination with an OWL Intuition energy monitor.
Just a note to say this is a feature I'm craving, especially with the recent erratic pricing. I have a dehumidifier on a timer that I would prefer to have run in one contiguous block each day, than to switch on and off in sporadic 30 minute intervals.
I know it would cost me more for the contiguous block, though as I think you've mentioned elsewhere, that might lend itself better to certain devices.

**Comment by markgdev** [comment]
@slug56, I've just merged this in, if you have any issues let me know!

**Comment by markgdev** [comment]
Actually, timers will only get created if requirements are specified, going to fix that.

**Comment by markgdev** [comment]
Now merged in with fix, if requirements aren't set then it'll get the best block for the whole time.

**Comment by slug56** [comment]
Looking good 🤓 I've got a single 10-hour block now, whereas before there were 2 or 3 30-minute blocks at different times. Will keep an eye over the next few days. Nice work!
