### ISSUE TITLE
Blank Custom Card

### ISSUE THREAD

**Issue by matthewjporter** [markgdev/home-assistant_OctopusAgile#12]
Hi Mark

Not actually sure when it started as I have not switch to Agile yet but I had the custom component running "installed" and had the rates card displying

However, now I am just getting a blank screen after putting in the latest custom omponent and card

I know it not much to go on and am going to try from a backup and replace with an older component and card but thought you might have an idea?

I am running on a PI with the latest build of hassio and other custom components are working fine

**Comment by matthewjporter** [comment]
Has anything changed in the config/setup as the latest version give me errors. I read about the mpan, auth etc so have added in and used !secrets

The following integrations and platforms could not be set up:

OctopusAgile
OctopusAgile.sensor
Please check your config.

But when I revert, it works absolutely fine

this is my current config:

`
OctopusAgile:
  mpan: !secret octopus_mpan
  serial: !secret octopus_serial
  auth: !secret octopus_auth
  region_code: !secret octopus_region
  showunits: false
  moneymakers:
  - switch.testbutton: null
  - climate.downstairs:
      params:
        temp: 25
  timers:
  - day_from: today
    day_to: tomorrow
    entity_id: switch.testbutton
    numHrs: 5
    paramms: null
    requirements:
      - day_from: today
        day_to: tomorrow
        numHrs: 1
        time_from: '19:00:00'
        time_to: '06:00:00'
      - day_from: tomorrow
        day_to: tomorrow
        numHrs: 1
        time_from: '10:00:00'
        time_to: '16:00:00'
    time_from: '19:00:00'
    time_to: '19:00:00'

  run_devices:
  - energy_time: 2.5
    entity_id: dish_washer
    run_before: '08:00:00'
    run_time: 1
  - energy_time: 2.5
    entity_id: washing_machine
    run_before: '08:00:00'
    run_time: 2
  - energy_time: 5
    entity_id: tumble_dryer
    run_before: '08:00:00'
    run_time: 2

sensor:
- platform: "OctopusAgile"
`

**Comment by tbutcher365** [comment]
I think the readme.md has a typo with paramms: null.

**Comment by matthewjporter** [comment]
> I think the readme.md has a typo with paramms: null.

Thanks, I have changed in my config, but still getting a blank card with the latest component, but when I roll back I get the custom-card with the Green, Red, Orange and Blue sections so its not the card

Must be either my config and the changes made or the component but as others have it working, must be in my config

Question on the config, when it mention's auth: i assume this is the Octopus API key?

**Comment by tbutcher365** [comment]
Correct on the key. Have you checked home-assistant.log for errors?

**Comment by markgdev** [comment]
Hi @matthewjporter, did you manage to get it going? Sorry for the delayed response, I’ve not had as much chance to work on this recently as I’d like. If the component isn’t loading then there should be something in the home assistant log relating to octopusagile, it’d be helpful to see anything from there.

**Comment by markgdev** [comment]
I think this is sorted? Going to close but feel free to reopen if not!

**Comment by Kosh42** [comment]
I'm getting this exact same issue here, but for me it's never worked (I only installed it yesterday). The entity is getting data fine, but the custom card is just coming back blank. Had  poke in the logs and it doesn't see to have anything related to this integration. 

Silly Q: I installed the integration via HACS, but the custom card manually (WGET the js from he terminal, then added to resources). Is this right, or have I caused it brain ache?

![blank custom card](https://user-images.githubusercontent.com/58401509/130285990-972f6ca0-c13a-45e6-bf0f-336e1f986720.png)
![populated entity](https://user-images.githubusercontent.com/58401509/130286002-56d8c663-cb6c-45db-9f57-3632d00075fb.png)

Either way, even without the card it's excellent work. Many thanks!

**Comment by Kosh42** [comment]
@matthewjporter - Is yours still behaving of has a more recent update caused you issues again?

**Comment by markgdev** [comment]
> I'm getting this exact same issue here, but for me it's never worked (I only installed it yesterday). The entity is getting data fine, but the custom card is just coming back blank. Had poke in the logs and it doesn't see to have anything related to this integration.
> 
> Silly Q: I installed the integration via HACS, but the custom card manually (WGET the js from he terminal, then added to resources). Is this right, or have I caused it brain ache?
> 
> ![blank custom card](https://user-images.githubusercontent.com/58401509/130285990-972f6ca0-c13a-45e6-bf0f-336e1f986720.png)
> ![populated entity](https://user-images.githubusercontent.com/58401509/130286002-56d8c663-cb6c-45db-9f57-3632d00075fb.png)
> 
> Either way, even without the card it's excellent work. Many thanks!

Have you cleared the cache in your browser? I seem to recall that causing me issues in the past.

**Comment by Kosh42** [comment]
Works a treat! Many thanks. 
> Have you cleared the cache in your browser? I seem to recall that causing me issues in the past.
