### ISSUE TITLE
DST Issue

### ISSUE THREAD

**Issue by dmelliott20** [markgdev/home-assistant_OctopusAgile#19]
![image](https://user-images.githubusercontent.com/13154453/84153186-78960700-aa5d-11ea-96ab-08f8ebec631a.png)

Looks like the pricing is out by an hour, anyone else having the same issue?

**Comment by markgdev** [comment]
You’re completely right, everything on the backend is in GMT rather than BST. I need to revisit how I deal with that, I think the agile api can provide local time but I haven’t had time to look at it. 

If you use the rates card it converts to local time/BST for display in Lovelace.

**Comment by dmelliott20** [comment]
Thanks. So the firing of the timers are unaffected by this?

Sent from my iPhone

On 9 Jun 2020, at 19:07, Mark Gardner <notifications@github.com> wrote:

﻿

You’re completely right, everything on the backend is in GMT rather than BST. I need to revisit how I deal with that, I think the agile api can provide local time but I haven’t had time to look at it.

If you use the rates card it converts to local time/BST for display in Lovelace.

**Comment by markgdev** [comment]
Nope, they should be all good. The only thing that it should affect is if you specify requirements in a timer, they will need to be GMT, which is obviously a bit rubbish when daylight savings ends and they’ll need changing. Hopefully I’ve got everything changed to local time by then though!

**Comment by dmelliott20** [comment]
Thanks!!

Sent from my iPhone

On 9 Jun 2020, at 20:40, Mark Gardner <notifications@github.com> wrote:

﻿

Nope, they should be all good. The only thing that it should affect is if you specify requirements in a timer, they will need to be GMT, which is obviously a bit rubbish when daylight savings ends and they’ll need changing. Hopefully I’ve got everything changed to local time by then though!
