### ISSUE TITLE
Disable another device whilst running a device 

### ISSUE THREAD

**Issue by ademobile** [markgdev/home-assistant_OctopusAgile#20]
When rates are low (for me below 3.5p per kW/h) I want to disable my gas water heater controller  (in my case Evohome) and enable my immersion heater. Once rates ago above set value I want to re-enable the gas water heater controller.

This would mean I get to heat water using be best cost method.

I hope this makes sense!

**Comment by markgdev** [comment]
Hi @ademobile, I think this might be easiest for you using an automation in home assistant based on the entity sensor.octopus_agile_current_rate. You can have it turn things on/off based on the value of that sensor by calling the homeassistant.turn_on/off service.
Let me know if that is enough or if there is something more you need?
