### ISSUE TITLE
Allow control of number of decimal places shown in custom card

### ISSUE THREAD

**Issue by B-Hartley** [markgdev/home-assistant_OctopusAgile#24]
Fitting the Agile Prices custom card on my iPhone screen is a challenge.
I've reduced it to 1 decimal place by changing the .js file  and it fits better.

Could this be a config option somehow ?

**Comment by markgdev** [comment]
This makes total sense, should be easy enough to add in 👍

**Comment by markgdev** [comment]
All done, you may need to clear cache for changes to take affect.
