### ISSUE TITLE
Streamline costs table

### ISSUE THREAD

**Issue by markgdev** [markgdev/home-assistant_OctopusAgile#5]
Is your feature request related to a problem? Please describe.
The costs table card is too bulky, remove seconds from time and allow user to disable units if desired.

**Comment by markgdev** [comment]
I quite like the units shown so will add an extra option to the config to allow it to be hidden if preferred.

**Comment by Creatish** [comment]
Looks good :)

**Comment by markgdev** [comment]
Pretty happy that this is working well so going to close.
