### ISSUE TITLE
British Summer Time and current rate

### ISSUE THREAD

**Issue by notJustageek** [markgdev/home-assistant_OctopusAgile#67]
**Describe the bug**
I'm not sure if this is a bug with this module or something within home assistant more generally.  Since the clocks changed this weekend, the current rate seems to be an hour out from what the rate should be for a given point in the day.

**To Reproduce**
1. Set the timezone to London
2. Check the sensor.octopus_agile_current_rate sensor
3. Look up the rate for the current time in octopusagile.rates
4. The current rate will be for the previous hour

**Expected behavior**
Expectation is that the rate for a given time will match that timecode in the octopusagile.rates attributes.

**Desktop (please complete the following information):**
 - OS: Universal
 - Browser Chrome

**Comment by B-Hartley** [comment]
Mine seem ok.
Is the time on your server set correctly?
Does the server have it's GMT time correct? and timezone and DST settings correct?

**Comment by notJustageek** [comment]
Sorry, just looked again and realised the times in octopusagile.rates are UTC encoded rather than local time.  Using the rates card it looks correct and the current rate matches the octopus website.
