### ISSUE TITLE
Homeassistant.loader reports [No 'version' key in the manifest file], this will not be allowed in a future version of Home Assistant.

### ISSUE THREAD

**Issue by GGW42** [markgdev/home-assistant_OctopusAgile#69]
**Is your feature request related to a problem? Please describe.**
**No Problem yet but may stop this add-on from working in the future.
The Log file asks "Please report this to the maintainer of 'octopusagile'"**

**Describe the solution you'd like**
**Give it a 'version key' please, i don't want it to stop working**

**Describe alternatives you've considered**
**NA**

**Additional context**

**Warning Message in "Home Assistant 2021.3.2" log file
2021-04-11 08:54:07 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'octopusagile'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'octopusagile'**

**Comment by markgdev** [comment]
Have you updated the component lately? I had to add this to get it working with HACS by default so should be sorted already. If you're running the latest version let me know as it means I did something wrong!

**Comment by GGW42** [comment]
Hi Mark,
Thanks for that, I couldn't see any reference to that error here and though you should know. I did an install a few months ago and hadn't noticed any changes since but I will re-install and see how it goes. Hopefully that is all it is.
@GGW42 @markgdev

**Comment by GGW42** [comment]
@markgdev . The new install seems to have fixed that problem, thank you.
Can we use that version Key in some way to tell us we are on an older version? The file dates were only a few weeks difference, so I though I was on the latest, a version number culd be useful. Thanks again, very useful program.
