### ISSUE TITLE
Login Text Block 

### ISSUE THREAD

**Issue by SHHA24** [markgdev/home-assistant_OctopusAgile#70]
hi when you install the integration you get a config block that asume asks for login and API credentials, but there is no text shown so dont know what order or what the items needed are? 

![octopusagile](https://user-images.githubusercontent.com/62449702/115757035-400dcc00-a396-11eb-83a2-52b128628b4d.jpg)

**Comment by markgdev** [comment]
You can close that form with nothing in, all the config is still done through the configuration.yaml file 👍

**Comment by SHHA24** [comment]
thanks got that working, in the config do you have an example of the full config file, as not sure how to add the sensors...
(Create a sensor for each of: current rate, previous rate and next rate)

**Comment by markgdev** [comment]
Sure, the example in the readme is the full config. You need this bit for the sensors:
`sensor:
- platform: "octopusagile" `

**Comment by SHHA24** [comment]
thanks works really well!
