### ISSUE TITLE
Integration shows blank card

### ISSUE THREAD

**Issue by dannytsang** [markgdev/home-assistant_OctopusAgile#76]
**Describe the bug**

**To Reproduce**
1. Configuration > Integrations > Add Integrations (button)
2. Find octopusagile in the list and click on it.
3. 3 fields appear with no labels.

**Expected behavior**
Labels near the fields so I know what I need to enter.

**Screenshots**
![image](https://user-images.githubusercontent.com/567982/119277268-8fa21a80-bc16-11eb-9bcc-77866f917126.png)

![image](https://user-images.githubusercontent.com/567982/119277280-a0eb2700-bc16-11eb-99cc-3e6f4798147c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 90.0.818.66 

**Additional context**
Installed via HACs version v0.1.1 of Octopus Agile.

If I configure in in configuration.yaml file using the example, the check config complains it is missing an integration.

**Comment by B-Hartley** [comment]
Configuration is through yaml at present. 
so nothing is entered here.

**Comment by dannytsang** [comment]
Got it. Thanks @B-Hartley
