### ISSUE TITLE
octopusagile does not have a valid version key in the manifest file and was blocked from loading

### ISSUE THREAD

**Issue by markcocker** [markgdev/home-assistant_OctopusAgile#79]
**Describe the bug**
Octopus Agile fails to load at Home Assistant startup due to message:
```
2021-06-03 17:38:46 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'octopusagile' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```

**To Reproduce**
1. Install latest `Octopus Agile` via HACS
2. Restarting Home Assistant
3.  View log at /config/logs

**Expected behavior**
No errors in log and Octopus Agile works.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 89

**Comment by tbutcher365** [comment]
What version are you using as the current code has a version number in the manifest.json?

**Comment by markcocker** [comment]
Ah my mistake. I had two version installed. I had assumed the one installed via HACS would overwrite the manually installed version, but they had different casing in the directory. I removed both and re-installed via HACS and working fine now thanks.
