### ISSUE TITLE
GUI config flow doesn't label fields

### ISSUE THREAD

**Issue by Mearman** [markgdev/home-assistant_OctopusAgile#87]
Not sure which data to put where because the label on the config flow aren't labeled.
Had a look at the page and your repo source and couldn't work out where it should be set
![image](https://user-images.githubusercontent.com/1331872/130315377-4effa9b9-f3ee-48d0-9a86-563ff9d5c5dd.png)

**Comment by markgdev** [comment]
Just leave it empty, all config is done in configuration.yml still.

**Comment by Mearman** [comment]
ohhhh. cheers

**Comment by mousemat86** [comment]
what are the fields that need filling? Leaving it empty isn't an option.

**Comment by markgdev** [comment]
Just got the x in the corner, no fields need filling.
