### ISSUE TITLE
0.5 is invalid for numHrs

### ISSUE THREAD

**Issue by tbutcher365** [markgdev/home-assistant_OctopusAgile#9]
You can't use 0.5 for numHrs in the timers. It appears the minimum value is 1 which means you always get at least 2 slots when one would be fine.

**Comment by markgdev** [comment]
I will take a look to see what’s causing that, it should just be multiplied by 2 to get the number of slots but must’ve done something silly!

**Comment by markgdev** [comment]
Just tested, looks like I fixed this but never closed the ticket.
