### ISSUE TITLE
Documentation confusion over Readme and 'latest' code version

### ISSUE THREAD

**Issue by d1964b** [markgdev/home-assistant_OctopusAgile#92]
I'm confused about what the documentation page is telling me about what the latest 'live' version of the software is. Specifically the main github 'code' page identifies the latest version as 0.1.1 but the readme.md on the same page gives an example of using the Go tariff. Looking throgh the 'releases' link , the code to support that tariff was introduced as part of 0.1.2-beta3. 
Has the readme.md file on the main 'Code' page got ahead of itself or is the beta3 release to be treated as the 'Latest' code ??

**Comment by markgdev** [comment]
I’ve been using 0.1.2-beta3 for a long time now since moving to go so it probably shouldn’t be beta anymore. I have to admit I’ve not given much love to the code since then as I’ve not really been making use the features it provides since moving from agile.
